dependencies:

  - role: jdauphant.nginx
    nginx_sites:
      default:
        - listen 80
        - location / { uwsgi_pass richard_backend; include /etc/nginx/uwsgi_params; }
        - location /static { alias {{ richard_dir }}/static; }
    nginx_configs:
      richard:
        - upstream richard_backend { server unix:///{{ richard_dir }}/richard.socket; }
