---
- name: richard user exists
  user: name="{{ richard_user }}" shell=/bin/bash state=present

- name: richard site directory exists
  file: path="{{ richard_dir }}" state=directory owner="{{ richard_user }}" group="{{ richard_group }}"

- name: richard is cloned
  git: repo="{{ richard_repo }}"
       dest="{{ richard_source }}"
       version="{{ richard_version }}"
  sudo_user: "{{ richard_user }}"

- name: install richard dependencies
  pip: name=".\[dev,postgresql\]"
       chdir="{{ richard_source }}"
       extra_args="-e"

- name: install uwsgi
  pip: name=uwsgi
       version=2.0.9

- name: richard syncdb
  environment:
    DJANGO_CONFIGURATION: "{{ richard_configuration }}"
  django_manage: >
    command="syncdb --noinput --migrate"
    app_path="{{ richard_source }}"
    settings=richard.config.settings
  sudo_user: "{{ richard_user }}"

- name: richard migrate
  environment:
    DJANGO_CONFIGURATION: "{{ richard_configuration }}"
  django_manage: >
    command=migrate
    app_path="{{ richard_source }}"
    settings=richard.config.settings
  sudo_user: "{{ richard_user }}"

- name: richard collectstatic
  environment:
    DJANGO_CONFIGURATION: "{{ richard_configuration }}"
  django_manage: >
    command="collectstatic --noinput"
    app_path="{{ richard_source }}"
    settings=richard.config.settings
  sudo_user: "{{ richard_user }}"

- name: richard uwsgi.ini
  template: >
    src=richard.uwsgi.ini.j2
    dest="{{ richard_uwsgi_ini }}"
    owner=root
    group=root
    mode=644

- name: richard init.conf
  template: >
    src=richard.uwsgi.conf.j2
    dest=/etc/init/richard.uwsgi.conf
    owner=root
    group=root
    mode=644

- name: richard.uwsgi service
  service: name=richard.uwsgi state=started enabled=yes
  tags: [service,richard]
